### ISSUE TITLE
Not showing in list of faces (LG watch Urbane)

### ISSUE THREAD

**Issue by ataranlen** [fathominfo/fathom-watchfaces#52]
Running the latest version of wear on my Urbane and installing all three of these watch faces on my nexus 5, none of these watch faces shows up in the android wear app or on my watch.

Watch: LG watch Urbane on wear v1.3
Phone: LG Nexus 5 on M dev preview 3

**Comment by benfry** [comment]
Do any watch faces from Google Play work with this unreleased Developer Preview version of the OS?

**Comment by ataranlen** [comment]
I've got the following watch faces installed from the play store, and they all show up in Android Wear and on the device.
Starwatch
Bits (requires wear 1.3)
Form
Shadow Clock
Secret Agent

**Comment by ataranlen** [comment]
Fixed with the latest version 1.1.1 on Bouncing Isaac, 1.1.2 on Gaze, and 1.1.1 on Coubertin Rings.

**Comment by benfry** [comment]
Great! Thanks for the update. We're still not sure why it wasn't working, but linking with the latest libraries and SDK did the trick.
